### ISSUE TITLE
[Bug] Submitting a lower treasury track

### ISSUE THREAD

**Issue by BehrangBahrami** [galaniprojects/Polkadot-Bounty-Manager#174]
| Name  | about | Parent ticket | Date |
| ------------- | ------------- | ------------- | ------------- |
| Treasury Track Bug | Submitting a wrong Treasury Track  | #108 | 19.09.2024 |
---
Description:

Depending on the amount of the proposed bounty, for both treasury track menus, it doesn't occur an error if you select a lower spender and submit.

---
1. Go to the bounty setup
2. fill the mandatory fields up
3. Give a bounty value for medium or big spender
4. Submit the bounty
5. On approval tab select small spender for treasury track
6. Submit
7. No error will occur
8. Go to the curator proposal tab
9. In treasury track select small spender 
10. Submit
11. Current behavior: No error will occur

**Expected behavior:** Submitting an approval or curator proposal shouldn't be possible if a lower treasury track is selected

---
**Test data:**
- OS: Mac
- Browser: Chrome 
- Version: 128.0.6613.139 (Official Build) (x86_64)
- URL: https://test.dm3b5qeja0nkd.amplifyapp.com/

**Comment by bill-pap** [comment]
Let's put this on hold for now, I think there is actually no error the chain would return for this, and I cannot replicate it on any test network.
I have asked a contact who deals with OpenGov issues about it and will let you know once I hear back from him

**Comment by bill-pap** [comment]
@BehrangBahrami I can confirm there is no error in this case.
I will update the functionality issue to remove the error. 
Please remove it from the test cases as well
