### ISSUE TITLE
[Bug] The Deposit and transaction fee don't change

### ISSUE THREAD

**Issue by BehrangBahrami** [galaniprojects/Polkadot-Bounty-Manager#186]
| Name  | about | Parent ticket | Date |
| ------------- | ------------- | ------------- | ------------- |
| Deposit and transaction fee  | These fields don't change depending on the treasury track and value  | #109 | 23.09.2024 |
---
Description:

Depending on the amount of the proposed bounty, the treasury track in approval tab will change automatically, but the treasury track on Curator Proposal tab stays always on small spender. 

---
1. Go to the bounty setup
2. fill the mandatory fields
3. Give a bounty value for medium or big spender
4. Submit the bounty
5. Go to the approval tab
6. On approval tab treasury track is set to the correct spender
7. Submit
8. Go to the curator proposal tab
9. change the value and treasury track
10. Deposit and transaction fee don't change

**Expected behavior:** The transaction fee doesn't change correctly depending on the treasury track and curator fee

---
**Test data:**
- OS: Mac
- Browser: Chrome 
- Version: 128.0.6613.139 (Official Build) (x86_64)
- URL: https://test.dm3b5qeja0nkd.amplifyapp.com/
![Image](https://github.com/user-attachments/assets/404ef404-b879-4d3c-812a-bd0055f0349c)
![Image](https://github.com/user-attachments/assets/180acb61-9904-41f8-9875-e40d83bf82fc)
![Image](https://github.com/user-attachments/assets/60425767-5683-40c6-94da-25041da64e54)
![Image](https://github.com/user-attachments/assets/df26a63f-3e9e-4c27-b096-14b2ddce5b94)
![Image](https://github.com/user-attachments/assets/4e4d276a-d8f5-4eeb-91f2-f088d176b037)
![Image](https://github.com/user-attachments/assets/0c49b6d1-8b2a-4d43-9e34-ab4885ebbebd)
![Image](https://github.com/user-attachments/assets/fd9c68e2-a00d-4d80-82b4-83a493d5c1ea)

**Comment by bill-pap** [comment]
@BehrangBahrami I'm deleting this ticket as it is redundant
