### ISSUE TITLE
Spending Track on Bounty Approval Referendum Screen

### ISSUE THREAD

**Issue by bill-pap** [galaniprojects/Polkadot-Bounty-Manager#32]
Dependent on #6 
The system displays a suggested spending track for the referendum based on the Bounty value. 
The user can still select a different track from the dropdown.

Available Tracks:
- Small Spender, up to 10,000 DOT
- Medium Spender, up to 100,000 DOT
- Big Spender, up to 1,000,000 DOT

![image](https://github.com/user-attachments/assets/6d2f0ea3-ea02-4f1b-a296-8c8995c56480)

**Comment by BehrangBahrami** [comment]
@bill-pap What is the default value of the drop-down menu suggested track?
