### ISSUE TITLE
[UI] Header and Footer

### ISSUE THREAD

**Issue by WaleedKTareen** [galaniprojects/Polkadot-Bounty-Manager#383]
- [x] In the header the current logo should be replaced with the one provided in the link.
- [x] Footer should include buttons feedback channels which are telegram and email. 
- [x] The telegram link would be "https://t.me/bounty_manager_feedback"
- [x] The email link would be  "bountymanager@galaniprojects.com".
- [x] Followed by "Imprint and Terms & Conditions" and "powered by Polkadot"

[Link to the footer](https://b-t-e.invisionapp.com/console/Bounty-Manager-clwqlb4za00oz017seqszhz01/cm48oz7y71c9y01cr55mm7w0j/play)

**Comment by arty-name** [comment]
![Image](https://github.com/user-attachments/assets/f93d35ac-777c-46c8-a254-3f591f8d8014)
![Image](https://github.com/user-attachments/assets/e803d276-cfec-45e9-a96e-a119145a1bb2)
