### ISSUE TITLE
[UI] Add Child Bounty

### ISSUE THREAD

**Issue by WaleedKTareen** [galaniprojects/Polkadot-Bounty-Manager#80]
This pop-up appears after clicking on the "NEW CHILD BOUNTY" button for New Child Bounty.

Included fields are: 

- [ ] Title "ADD NEW CHILD BOUNTY
- [ ] Number and name of bounty"
- [ ] Note
- [ ] Input field for value.
- [ ] Input field for the title.
- [ ] Input field with description (Functionality dependent on collaboration with Polkassembly.) 
- [ ] Estimated transaction Fee
- [ ] "X" and "Sign" buttons

Functionality galaniprojects/Polkadot-Bounty-Manager#81 
Diagram galaniprojects/Bounty-Manager-Issues#3 

[Link to Invision](https://b-t-e.invisionapp.com/console/Bounty-Manager-clwqlb4za00oz017seqszhz01/cm20khqsa0p8l01ag0s0l3wgh/play)

[Link to Figma](https://www.figma.com/design/9sDmKtO9BZIGMUwl5vMnlM/Bounty-Manager-Prototype?node-id=13-162505&node-type=section&t=LygHz3OEtNYQbg5F-0)

**Comment by BlertaSunCacti** [comment]
How to test:
1. Go to https://test.dm3b5qeja0nkd.amplifyapp.com/curator-actions
2. Click on the "Accept" button next to the "Curator Rule" inside a parent bounty section
3. Check that the UI works both on Mobile and Desktop viewports.

**Comment by WaleedKTareen** [comment]
@BlertaAtGalaniprojects @abdulmth @BehrangBahrami updated issue 07.10.2024
